### ISSUE TITLE
Expose type declarations

### ISSUE THREAD

**Issue by jarimayenburg** [daanjo3/torn-api-client#6]
Typescript types don't seem to be exposed properly yet and there is no DefinitelyTyped module.

![image](https://user-images.githubusercontent.com/11874892/159084348-6ea602bd-bf61-4b08-b566-ff04b433ddcb.png)

**Comment by daanjo3** [comment]
No entry point was yet defined for the package. This is done now, so the class and types should be resolveable now.

Patched in 0.1.2.
